// To FitBit
export const UPDATE_UI = 'UPDATE_UI';

// To Companion
export const UPDATE_HEART_RATE = 'UPDATE_HEART_RATE';
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS';
export const PREVIOUS_TRACK = 'PREVIOUS_TRACK';
export const NEXT_TRACK = 'NEXT_TRACK';
export const PAUSE_MUSIC = 'PAUSE_MUSIC';
export const PLAY_MUSIC = 'PLAY_MUSIC';
export const TOGGLE_HEART_RATE_SHUFFLE = 'TOGGLE_HEART_RATE_SHUFFLE';
export const UPDATE_PLAYER_STATE = 'UPDATE_PLAYER_STATE';

export const OPEN_MENU = 'OPEN_MENU';
export const SELECT_PAGE = 'SELECT_PAGE';

export const SCROLL_DOWN_PLAYLIST = 'SCROLL_DOWN_PLAYLIST';
export const SCROLL_UP_PLAYLIST = 'SCROLL_UP_PLAYLIST';
export const SELECT_PLAYLIST = 'SELECT_PLAYLIST';
export const LOGO_CLICK = 'LOGO_CLICK';

export const INCREASE_VOLUME = 'INCREASE_VOLUME';
export const DECREASE_VOLUME = 'DECREASE_VOLUME';

export const PHYSICAL_KEY_PRESS = 'PHYSICAL_KEY_PRESS';
